global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: "api-gateway"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:9000"] ## only for demo purposes don't use host.docker.internal in production
  - job_name: "user-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: "User Service"
  - job_name: "post-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: "Post Service"
  - job_name: "like-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: "Like Service"
  - job_name: "email-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8083"] ## only for demo purposes don't use host.docker.internal in production
        labels:
          application: "Email Service"
